In [2]:
##Question 1 https://www.hackerrank.com/challenges/np-arrays/problem

In [3]:
import numpy

def arrays(arr):
    rev_arr = arr[::-1]
    ndarray = numpy.array(rev_arr, float)
    
    return ndarray
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [4]:
##Question 2 https://www.hackerrank.com/challenges/np-shape-reshape/problem

In [5]:
import numpy as np

def arrays(arr):
    n=np.array(arr)
    return np.reshape(n,(3,3))

l=list(map(int,input("").split()))
x=arrays(l)
print(x)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
##Question 3 https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem

In [7]:
import numpy
r, c = map(int, input().split())
array = numpy.array([input().split() for _ in range(r)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
##Question 4 https://www.hackerrank.com/challenges/np-concatenate/problem

In [8]:
import numpy
a,b,c = map(int, input().split())
m = numpy.array([input().split() for _ in range(a)], int)
n = numpy.array([input().split() for _ in range(b)], int)
print(numpy.concatenate((m, n)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
##Question 5 https://www.hackerrank.com/challenges/np-zeros-and-ones/problem

In [9]:
import numpy as np
x=list(map(int,input().split()))
print(np.zeros(x,np.int))
print(np.ones(x,np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [10]:
##Question 6 https://www.hackerrank.com/challenges/np-eye-and-identity/problem

In [11]:
import numpy as np
x,y=map(int,input("").split())
np.set_printoptions(legacy='1.13')
print(np.eye(x,y, k = 0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
##Question 7 https://www.hackerrank.com/challenges/np-array-mathematics/problem

In [13]:
import numpy as np
x,y = map(int, input().split())
a,b = (np.array([input().split() for _ in range(x)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [14]:
##Question 8 https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem

In [15]:
import numpy as np
l=list(map(float,input("").split()))
np.set_printoptions(legacy='1.13')
x=np.array(l)
print(np.floor(x))
print(np.ceil(x))
print(np.rint(x))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [16]:
##Question 9 https://www.hackerrank.com/challenges/np-sum-and-prod/problem

In [17]:
import numpy
x,y = map(int, input().split())
n = numpy.array([input().split() for _ in range(x)],int)
print(numpy.prod(numpy.sum(n, axis=0), axis=0))

2 2
1 2
3 4
24


In [18]:
##Question 10 https://www.hackerrank.com/challenges/np-min-and-max/problem

In [19]:
import numpy as np
x,y= list(map(int, (input().split())))
n = np.array([list(map(int,(input().split()))) for i in range(int(x))])
print(np.max(np.min(n, axis = 1), axis = None))

4 2
2 5
3 7
1 3
4 0
3


In [20]:
##Question 11 https://www.hackerrank.com/challenges/np-mean-var-and-std/problem

In [21]:
import numpy
x,y = map(int, input().strip().split())
my_array = numpy.array([ input().strip().split() for _ in range(x) ], int)
print(numpy.mean(my_array, axis = 1))
print(numpy.var(my_array, axis = 0))
print(round(numpy.std(my_array, axis = None),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [22]:
##Question 12 https://www.hackerrank.com/challenges/np-dot-and-cross/problem

In [23]:
import numpy
n=int(input())
A,B=[(numpy.array([list(map(int,input().split())) for _ in range(n)])) for _ in range(2)]
print (numpy.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [24]:
##Question 13 https://www.hackerrank.com/challenges/np-inner-and-outer/problem

In [25]:
import numpy
A=numpy.array(list(map(int,input().split())))
B=numpy.array(list(map(int,input().split())))
print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [26]:
##Question 14 https://www.hackerrank.com/challenges/np-polynomials/problem

In [27]:
import numpy
print(numpy.polyval(list(map(float,input().split())),float(input())))

1.1 2 3
0
3.0


In [28]:
##Question 15 https://www.hackerrank.com/challenges/np-linear-algebra/problem

In [29]:
import numpy
print(round(numpy.linalg.det(numpy.array([list(map(float,input().split())) 
        for _ in range(int(input()))])),2))

2
1.1 1.1
1.1 1.1
0.0
